version: '3'

services:
  dev:
    build:
      context: . 
      dockerfile: Dockerfile
    working_dir: /work
    volumes:
      - ./:/work
      - rust_target:/work/rust_target
    tty: true
    environment:
      CARGO_BUILD_TARGET_DIR: /work/rust_target

volumes:
  rust_target: